# Generated by Django 4.2.2 on 2023-06-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=255)),
                ('ItemPrice', models.FloatField()),
                ('ItemStock', models.IntegerField()),
                ('ItemImage', models.CharField(max_length=2550)),
            ],
        ),
    ]
